### PR TITLE
Add plugin options

### LINKED ISSUE #18: Document how do we pass in and reference options in plugins

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves #18 

I couldn't figure out a good place for it, maybe I'll have to do a little reorganizing.

cc @amasad @zpao

### CODE REVIEW

**Comment by zpao** [comment]
Thanks James! The one question that I think still isn't clearly answered is if `state.opts.option1` is unique per plugin or if two plugins accepting `option1` will clash. Perhaps it's just my personal experience with jstransform where that was a globally mutable object that is making me have questions about this…

**Comment by thejameskyle** [comment]
Oh they are totally separate from each other, I'll clarify that.

**Comment by zpao** [comment]
Thanks, you're the best!

**Comment by hzoo** [comment]
Do we want to link to that part or add it to http://babeljs.io/docs/plugins/#options

**Pull request merged**
