### PR TITLE
修改某些错别字

### PR DESCRIPTION
**Pull request by jiangqifan**
"数中的位置" -> "树中的位置"
"改作用于" -> "该作用域"

### CODE REVIEW

**Comment by thejameskyle** [comment]
Translations are not managed in this repository, they are managed through Crowdin. See https://github.com/thejameskyle/babel-plugin-handbook/blob/master/CONTRIBUTING.md

cc @nightire

**Comment by nightire** [comment]
OK，I'll fix this.

**Comment by nightire** [comment]
@thejameskyle Done. Thanks to @jiangqifan

**Comment by thejameskyle** [comment]
Docs have been updated

**Pull request closed without merging**
