### PR TITLE
Adds a jsbin link

### PR DESCRIPTION
**Pull request by brigand**

### CODE REVIEW

**Comment by thejameskyle** [comment]
People should use http://astexplorer.net not jsbin

**Comment by brigand** [comment]
astexplorer doesn't allow writing babel plugins. The intention was to have a simple sandbox to write plugins in without setting up a project and to use as a live pastebin for asking for help e.g. on slack.

**Comment by thejameskyle** [comment]
Yes it does, click transform

**Comment by brigand** [comment]
Ah cool :-)

**Comment by thejameskyle** [comment]
No, I was going to go through and add interactive links of the examples. See #30

**Pull request closed without merging**
