### PR TITLE
Add translation for Simplified Chinese (/translations/zh-hans.md)

### PR DESCRIPTION
**Pull request by nightire**
This is the first edition of Simplified Chinese translation, reviews are welcome.

### CODE REVIEW

**Comment by thejameskyle** [comment]
Damn @nightire you're awesome! 

As mentioned in https://github.com/thejameskyle/babel-plugin-handbook/issues/29 these translations are going to be managed by software that can make sure things stay up to date. I'll spend my weekend doing that.

**Comment by thejameskyle** [comment]
I migrated all of these translations to Crowdin and your translation is now available at: https://github.com/thejameskyle/babel-plugin-handbook/tree/master/translations/zh-CN

Thanks!

**Comment by nightire** [comment]
@thejameskyle :+1: you're welcome

**Comment by hzoo** [comment]
Awesome job :+1:

**Pull request closed without merging**
